nohup: ignoring input
  - (Training)   :   0%|          | 0/1892 [00:00<?, ?it/s]  - (Training)   :   0%|          | 0/1892 [00:00<?, ?it/s]  - (Training)   :   0%|          | 0/1892 [00:00<?, ?it/s]                                                                                                                                                                                 [*] Start training the model with multi-GPUs [1, 2, 3].

epoch: [0/10000]
Traceback (most recent call last):
  File "train.py", line 266, in <module>
    mp.spawn(train, 
  File "/home/joonsun/miniconda3/envs/nmt/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 199, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/joonsun/miniconda3/envs/nmt/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 157, in start_processes
    while not context.join():
  File "/home/joonsun/miniconda3/envs/nmt/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 118, in join
    raise Exception(msg)
Exception: 

-- Process 2 terminated with the following error:
Traceback (most recent call last):
  File "/home/joonsun/miniconda3/envs/nmt/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/home/joonsun/nmt-practice-pytorch/train.py", line 171, in train
    print_performances('Training', train_loss, train_acc, start_time)
NameError: name 'print_performances' is not defined

port, world_size, start_daemon, timeout)
RuntimeError: Address already in use

